2022-01-16 15:34:02,588 (7f41b6e35848) :  INFO (core:349) - Starting framework core - Version: 2.6.3, Build: f113340 (Wed Jan 12 18:34:40 UTC 2022)
2022-01-16 15:34:02,588 (7f41b6e35848) :  DEBUG (core:361) - Using the elevated policy
2022-01-16 15:34:02,588 (7f41b6e35848) :  DEBUG (core:450) - Starting runtime component.
2022-01-16 15:34:02,589 (7f41b6e35848) :  DEBUG (core:450) - Starting caching component.
2022-01-16 15:34:02,589 (7f41b6e35848) :  DEBUG (core:450) - Starting data component.
2022-01-16 15:34:02,589 (7f41b6e35848) :  DEBUG (core:450) - Starting networking component.
2022-01-16 15:34:02,589 (7f41b6e35848) :  DEBUG (networking:265) - No cookie jar found
2022-01-16 15:34:02,590 (7f41b6e35848) :  DEBUG (networking:428) - Setting the default network timeout to 20.0
2022-01-16 15:34:02,590 (7f41b6e35848) :  DEBUG (core:450) - Starting localization component.
2022-01-16 15:34:02,590 (7f41b6e35848) :  INFO (localization:409) - Setting the default locale to en-us
2022-01-16 15:34:02,590 (7f41b6e35848) :  DEBUG (core:450) - Starting messaging component.
2022-01-16 15:34:02,591 (7f41b6e35848) :  DEBUG (core:450) - Starting debugging component.
2022-01-16 15:34:02,591 (7f41b6e35848) :  DEBUG (core:450) - Starting services component.
2022-01-16 15:34:02,591 (7f41b6e35848) :  DEBUG (core:450) - Starting myplex component.
2022-01-16 15:34:02,591 (7f41b3d96b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/system/messaging/clear_events/tv.plex.agents.series'
2022-01-16 15:34:02,591 (7f41b6e35848) :  DEBUG (core:450) - Starting notifications component.
2022-01-16 15:34:02,677 (7f41b6e35848) :  DEBUG (accessor:68) - Creating a new model access point for provider tv.plex.agents.series in namespace 'metadata'
2022-01-16 15:34:02,680 (7f41b6e35848) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2022-01-16 15:34:03,013 (7f41b6e35848) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2022-01-16 15:34:03,016 (7f41b6e35848) :  CRITICAL (runtime:1299) - Exception getting hosted resource hashes (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-f11334058/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 1293, in get_resource_hashes
    json = self._core.networking.http_request("http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes", timeout=10).content
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-f11334058/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 242, in content
    return self.__str__()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-f11334058/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 220, in __str__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-f11334058/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 158, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

2022-01-16 15:34:03,023 (7f41b3b5eb38) :  DEBUG (services:265) - Plug-in is not daemonized - loading services from system
2022-01-16 15:34:03,023 (7f41b6e35848) :  DEBUG (runtime:1117) - Created a thread named 'load_all_services'
2022-01-16 15:34:03,024 (7f41b6e35848) :  DEBUG (runtime:1117) - Created a thread named 'get_server_info'
2022-01-16 15:34:03,024 (7f41b3b11b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400'
2022-01-16 15:34:03,025 (7f41b3b5eb38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_'
2022-01-16 15:34:03,026 (7f41b6e35848) :  DEBUG (core:150) - Finished starting framework core
2022-01-16 15:34:03,026 (7f41b6e35848) :  DEBUG (core:560) - Loading plug-in code
2022-01-16 15:34:03,027 (7f41b6e35848) :  DEBUG (core:566) - Finished loading plug-in code
2022-01-16 15:34:03,028 (7f41b6e35848) :  DEBUG (agentkit:1132) - Creating new agent class called PlexSeries
2022-01-16 15:34:03,028 (7f41b6e35848) :  DEBUG (agentkit:937) - Updating agent information: [{'media_types': ['TV_Show'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': None, 'languages': [], 'persist_stored_files': True, 'version': 0, 'primary_provider': True, 'prefs': True, 'name': 'Plex TV Series'}]
2022-01-16 15:34:03,029 (7f41b6e35848) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0FnZW50U2VydmljZTpVcGRhdGVJbmZv/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQo1CmRpY3QKbGlzdApkaWN0Cmxpc3QKbGlzdAoyCnMyMQp0di5wbGV4LmFnZW50cy5zZXJpZXNzMTAKaWRlbnRpZmllcnIxCnMxMAphZ2VudF9pbmZvMQpyMgoxMApyMwpzMTEKbWVkaWFfdHlwZXNuczEyCmFjY2VwdHNfZnJvbW5zMTQKZmFsbGJhY2tfYWdlbnRuczE0CmNvbnRyaWJ1dGVzX3RvcjQKczkKbGFuZ3VhZ2VzYjFzMjAKcGVyc2lzdF9zdG9yZWRfZmlsZXNpMApzNwp2ZXJzaW9uYjFzMTYKcHJpbWFyeV9wcm92aWRlcmIxczUKcHJlZnNzMTQKUGxleCBUViBTZXJpZXNzNApuYW1lMQpzNwpUVl9TaG93MApyMAo_'
2022-01-16 15:34:03,030 (7f41b3b11b38) :  DEBUG (core:538) - Machine identifier is befe4766b9f0ea72ec61f449f992356cdef0d4ca
2022-01-16 15:34:03,030 (7f41b3b11b38) :  DEBUG (core:539) - Server version is 1.25.3.5409-f11334058
2022-01-16 15:34:03,035 (7f41b3b5eb38) :  DEBUG (services:362) - Loaded services
2022-01-16 15:34:03,038 (7f41b3b34b38) :  DEBUG (services:438) - No shared code to load
2022-01-16 15:34:03,039 (7f41b6e35848) :  CRITICAL (sandbox:298) - Function named 'Start' couldn't be found in the current environment
2022-01-16 15:34:03,039 (7f41b6e35848) :  INFO (core:611) - Started plug-in
2022-01-16 15:34:03,039 (7f41b6e35848) :  DEBUG (socketinterface:160) - Starting socket server
2022-01-16 15:34:03,040 (7f41b6e35848) :  DEBUG (runtime:1117) - Created a thread named 'start'
2022-01-16 15:34:03,040 (7f41b6e35848) :  INFO (socketinterface:184) - Socket server started on port 42613
2022-01-16 15:34:03,040 (7f41b6e35848) :  INFO (pipeinterface:25) - Entering run loop
2022-01-16 15:34:03,040 (7f41b6e35848) :  DEBUG (runtime:717) - Handling request GET /:/prefixes
2022-01-16 15:34:03,041 (7f41b6e35848) :  DEBUG (runtime:814) - Found route matching /:/prefixes
2022-01-16 15:34:03,042 (7f41b6e35848) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 146 bytes
